# Generated by Django 5.1.4 on 2025-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceItem',
            fields=[
                ('insurance_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='보험코드')),
                ('name', models.CharField(max_length=100, verbose_name='품명')),
                ('specification', models.CharField(max_length=100, verbose_name='규격')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='금액')),
                ('expiry_date', models.DateField(verbose_name='유효기간')),
            ],
        ),
    ]
